### PR TITLE
Update CPUs database

### PR DESCRIPTION
**Pull request by X0rg**
Hi @anrieff,

Some minor changes for AMD and Intel databases.

**Intel-related changes:**
* Use `data->sgx.present` to detect Skylake CPU (because your comment about `CPU_FEATURE_SGX`)
* Recognise Core m[357] CPUs
* Recognise more Broadwell/Skylake/Kaby Lake CPUs

**AMD-related changes:**
* Reorganise CPUs since K10, ordering by Family number
* Fix extended family value for some APUs (some of them were not converted from hexadecimal to decimal)
* Proposal Zen support

**Questions:**
* In fact, supporting Ryzen doesn't require extra-work (unlike Intel CPUs), right? See the `//FIXME` on line 261.
* For some APUs, the `l2cache` value of structure `match_entry_t` is set: is it really needed ?

### CODE REVIEW

**Comment by anrieff** [comment]
Hi @X0rg,

on your questions:
1) No, usually they don't require additional detection via features. Technically Intels shouldn't either, but the problem there is that, for example Sandy Bridge i3, i5, i7 all have the same family/model/ext_model, but we need to give them different codenames to reflect i<number> . The current matchtable format cannot extract characters out from the CPU brand string, which would have made that easy and removed the necessity to do assign model codes like CORE_IVYx. I'll probably do that soon, to make the matchtable slightly more generic.

2) `l2_cache` is sometimes needed to differentiate CPUs whose codenames differ if cache is different and that's the only difference. From the old K7 times I remember the Barton<->Thorton example, but there are others as well. If you can do detection without specifying cache that's great.

On your changes, I have questions,
1) Have you tested them via `make test` (or `make test-old`, if the other one errors out)?
2) I'm kind of reluctant adding your "if it has SGX, then it's Skylake" changes because of future problems like issue #81. Also, see how you needed to add new codes for M3/5/7. This is not composable. What if Intel decide tomorrow to add another line, prefixed as 'f'? Should we have another set, CORE_SKYLAKEF3? As mentioned in answer (1) above, I'm thinking of expressing these more generally, probably is bitmasks of features found in the brand string (e.g., is the number 3, 5 or 7? is the prefix 'i' or 'm'? Is it Xeon? etc.). For that reason I'll merge your PR after some modifications.

Thank you for all other additions, I'll merge tomorrow after said simplifications.

**Comment by X0rg** [comment]
About my questions:
1. Ok, I understand. BTW, I think model codes will be required for Ryzen **3** (**4** cores/8 threads) and Ryzen **5** (**4** cores/8 threads for 1500X, **6** cores/12 threads for 1600X).

2. So, don't specify them:  803a062.

About your questions:
1. Indeed, I forgot to do it. Since  bb4141a, `All successfull!`.

2. Yes, it was useless to use `CORE_SKYLAKE` for Skylake, after all, Broadwell and Skylake don't have the same family/model/ext_model values. This is partially reverted in 8f94a9d, but I haven't changed anything about Core m[357].

**Comment by anrieff** [comment]
OK, writing the bit feature extraction now

**Comment by anrieff** [comment]
The new matchtable format is ready, see the commits from today.

**Comment by X0rg** [comment]
Yup, I'm looking at that.
It seems to avoid detection problems caused by some instructions (like RdRand or SGX), that's a good new.

**Pull request merged**
