### PR TITLE
add build support for debian jessie

### PR DESCRIPTION
**Pull request by gdbdzgd**
dpkg-buildpackage build debian packages

	new file:   debian/README.Debian
	new file:   debian/README.source
	new file:   debian/changelog
	new file:   debian/compat
	new file:   debian/control
	new file:   debian/copyright
	new file:   debian/docs
	new file:   debian/libcpuid-dev.install
	new file:   debian/libcpuid-doc.docs
	new file:   debian/libcpuid.install
	new file:   debian/rules
	new file:   debian/source/format

Signed-off-by: Zhang, Guodong <gdzhang@linx-info.com>

### CODE REVIEW

**Comment by gdbdzgd** [comment]
merge add build support for debian

**Comment by gdbdzgd** [comment]
add build support for debian

**Comment by gdbdzgd** [comment]
add build support for debian

**Comment by anrieff** [comment]
Hi,
I looked into your pull request, but it seems to contain a bunch of placeholders for info. Am I supposed to edit that info after merging?

**Comment by gdbdzgd** [comment]
of course, you can, i just pack this for debian jessie, and i am not add any info for this packages, by the way you should change debian/changelog the version number 0.21-1 -> 0.21, im pleasure test build on  debian after you change this files

**Pull request closed without merging**
