### PR TITLE
Append cache size to codename at runtime

### PR DESCRIPTION
**Pull request by wdlkmpx**
Instead of hard coding it in the cpudb_intel struct

This is just an idea i had

### CODE REVIEW

**Comment by anrieff** [comment]
I think this is a bit too broad in a lot of cases. For example, AMD K7 cores Thoroughbred and Barton only differ in the amount of cache - Thoroughbred has 256K while Barton has 512K. There's no difference in the cores besides that. Naming them "Thoroughbred 256K" and "Barton 512K" sounds like a tautology - their codenames already precisely specify the cache amount.

I think cache size shouldn't be included in cpu_codename if there is only one size for this particular CPU type. E.g., "Thoroughbred" should remain "Thoroughbred". When there are several related cores with the same broad codename, but differing caches (e.g. "Yorkfield 2M/3M/6M"), cache could be listed. I would approach it like this: in cpudb_intel, use names like "Yorkfield (Core 2 Quad) $$", where the $$ is a placeholder. Then, in match_cpu_codename(), you could check if matchtable[bestindex].name contains the placeholder, in which case you can replace it with the actual cache amount.

Of course, the placeholder can be something else than "$$", but I like the association $$→cash→cache :)

**Comment by wdlkmpx** [comment]
Sound good although the way it is now is very informative. I think a codename without cache size would also be ok.

But talking about codenames, i tested 2 cpus a few days ago and both were misreconigzed (both of them aren't  in the cpudbs either). In some cases I think it would be a good idea to use model names for quick recognition, such as P6100 TXXXX EXXX UXXX, this info is in brandstr

... new 1st struct ...
{ ARRANDALE, "P6000 P6100 P6200 P6300" },
.....

Then a function that parses each word and verifies with strstr against brandstr... I have written one..

**Comment by anrieff** [comment]
I agree that the brand string is a very useful piece of info, especially when the processor is new and libcpuid doesn't detect it well. I think that any sane tool that uses libcpuid as the backend should show both (codename and brand string; speaking of which, it should show cache size as well). I don't think libcpuid should revert to show the brand string if the detection fails. An "Uknown CPU" is a good enough output in this case, and an impetus to improve things. BTW, did you submit the two unrecognized CPUs [here](http://libcpuid.sourceforge.net/bugreport.php)?

**Comment by wdlkmpx** [comment]
I think this pull is good, but only as an exercise.

Model number appears in most modern intel cpus, so it's a good idea to use them whenever possible.

Here is an example:
http://pastebin.com/0XptyAPh

I'll gladly add a new .c file for intel recog. I've been checking many cpu-z screenshots and downloading many cpu-world pages... they banned my ip range and also the proxies i used hahaha. So it's easy for me to know what to do to increase libcpuid's reliability

**Pull request closed without merging**
