### PR TITLE
Use APIC ID to determine CPU topology

### PR DESCRIPTION
**Pull request by X0rg**
libcpuid is missing some information about cache sharing.

Examples:
- AMD Athlon X4 860K (#97): 4 cores with CMT, with 2 cores sharing the same L2 cache.
- Intel Alder Lake micro-architecture (#157): there is a dedicated L2 cache for each P-cores, but one L2 cache shared by 4 E-cores.

For Intel CPUs, APIC ID is helpful, here is a sample:
```
Cache L2 summary:
Cache ID 00000000 is shared between 2 logical CPUs
Cache ID 00000008 is shared between 2 logical CPUs
Cache ID 00000010 is shared between 2 logical CPUs
Cache ID 00000018 is shared between 2 logical CPUs
Cache ID 00000020 is shared between 2 logical CPUs
Cache ID 00000028 is shared between 2 logical CPUs
Cache ID 00000030 is shared between 4 logical CPUs
Cache ID 00000038 is shared between 4 logical CPUs

Cache L3 summary:
Cache ID 00000000 is shared between 20 logical CPUs
```

To quote @Umio-Yasuno:
> Golden Cove has 2-threads per core, Gracemont has 1-thread per core.

So, in that case, we can observe that there are 6 Golden Cove cores (0x00000000 to 0x00000028) and 8 Gracemont cores (0x000000030 and 0x00000038), i.e. 6x1.25 MB and 2x2 MB for L2 cache.

New fields can be added into `struct cpu_id_t` to expose the count for each cache level.

### CODE REVIEW

**Comment by X0rg** [comment]
Hello @anrieff,

I found on Zen-based CPUs, `cpu_id_t::l3_cache` is the total of L3 size for the whole CPU, while `cpu_id_t::l1_cache` and `cpu_id_t::l2_cache` are the size inside physical cores.
For Zen 1 and Zen 2, there are 2 CCX by CCD, like this:
zen-ccx
So, for instance, on my Ryzen 3600X, I have 2 CCX with 3 cores enabled by CCX (i.e. 2/8 cores are factory disabled on the die), meaning that there are 2x16 MB of L3 cache, not 1x32 MB.

It seems related to the fact we are not using CPU topology to determine cache info for AMD CPUs while we use it for Intel CPUs.
The deterministic way is the same for both vendors (Intel stores it in CPUID 00000004h, and AMD in CPUID 8000001Dh).
In af03af12066e099c19f5169f4029b843e38b61c1, I updated the way how we determine cache information on recent AMD CPUs, thus I had to update some tests (I consider previous values wrong and I see this change like an improvement to be honest).

The goal of that is to address this comment you wrote a long tile ago in #97:

> [...] Ideally, you should be able to compute that by `cpu_id_t::num_cores` × `cpu_id_t::l2_cache`. As you note, on i7 6700 you'll get the correct number; on the 860K you'd get 4*2MB = 8MB which is incorrect. 

As seen with AMD CMT and Intel hybrid CPUs, `cpu_id_t::num_cores` × `cpu_id_t::l2_cache` is not a correct way to compute total L2 cache size: the number of Ln caches depends of CPU topology.
In 7764702723df8652d5c00346fbd444248385aaee, I added a way to get cache ID, so we can count how many caches there are for each level.
In other words, the total cache size for level N is  `cpu_id_t::ln_num` × `cpu_id_t::ln_cache`.

Example of output for AMD Ryzen 5 3600X:
```
CPU Info for type #0:
------------------
  arch       : x86
  purpose    : general
  vendor_str : `AuthenticAMD'
  vendor id  : 1
  brand_str  : `AMD Ryzen 5 3600X 6-Core Processor             '
  ...
  num_cores  : 6
  num_logical: 12
  tot_logical: 12
  affi_mask  : 0x00000FFF
  L1 D cache : 32 KB
  L1 I cache : 32 KB
  L2 cache   : 512 KB
  L3 cache   : 16384 KB
  L4 cache   : -1 KB
  ...
  L1D num    : 6
  L1I num    : 6
  L2 num     : 6
  L3 num     : 2
  L4 num     : -1
```
We can see 2 L3 caches (one per CCX), so 2x16 MB = 32 MB ([as specified by AMD](https://www.amd.com/en/products/cpu/amd-ryzen-5-3600x)).

Example of output for Intel i9 12900HK:
```
CPU Info for type #0:
------------------
  arch       : x86
  purpose    : performance
  vendor_str : `GenuineIntel'
  vendor id  : 0
  brand_str  : `12th Gen Intel(R) Core(TM) i9-12900HK'
  ...
  num_cores  : 6
  num_logical: 12
  tot_logical: 20
  affi_mask  : 0x00000FFF
  L1 D cache : 48 KB
  L1 I cache : 32 KB
  L2 cache   : 1280 KB
  L3 cache   : 24576 KB
  L4 cache   : -1 KB
  ...
  L1D num    : 6
  L1I num    : 6
  L2 num     : 6
  L3 num     : 1
  L4 num     : -1
  ...
CPU Info for type #1:
------------------
  arch       : x86
  purpose    : efficiency
  vendor_str : `GenuineIntel'
  vendor id  : 0
  brand_str  : `12th Gen Intel(R) Core(TM) i9-12900HK'
  ...
  num_cores  : 8
  num_logical: 8
  tot_logical: 20
  affi_mask  : 0x000FF000
  L1 D cache : 32 KB
  L1 I cache : 64 KB
  L2 cache   : 2048 KB
  L3 cache   : 24576 KB
  L4 cache   : -1 KB
  ...
  L1D num    : 8
  L1I num    : 8
  L2 num     : 2
  L3 num     : 1
  L4 num     : -1
  ...
```
We can see there are 6 L2 caches for performance cores, while there are 2 L2 caches for efficiency cores (4 E-cores share the same L2 cache).

I just have a concern about one point: on Zen CPUs, there are physically several L3 caches (one by CCX), but on Intel hybrid CPUs, the same L3 cache is shared between P-cores and E-cores.
@anrieff what do you think we should do with `cpu_id_t` to avoid ambiguities? Is the `cpu_id_t::ln_num` field okay for you? Shall I add more fields in `system_id_t` and/or `cpu_id_t` to add more information about cache topology?

**Comment by anrieff** [comment]
Ah, I see, these were the other changes to data structures you were mentioning a few days ago.
Yes, adding the proposed fields (`cpu_id_t::l*_num`) seems a very good idea. I would only suggest to rename it to e.g. `l2_instances`, as otherwise `l2_num` seems a bit cryptic to me.

**Comment by X0rg** [comment]
> Yes, adding the proposed fields (`cpu_id_t::l*_num`) seems a very good idea. I would only suggest to rename it to e.g. `l2_instances`, as otherwise `l2_num` seems a bit cryptic to me.

Indeed, I renamed it in 1e7045b4ac313fb6d339566ae76ed6929456b7f0.

Also, I added a grant total inside `system_id_t` in 7da888f5ba4556314fb0a23f8e2efa73986744ee: the goal is if `system->cpu_types[0].l3_instances == 1` and `system->cpu_types[1].l3_instances == 1` but `system->l3_total_instances == 1`, it indicates the L3 instance in type 0 (P-cores) and type 1 (E-cores) is common to both types of core.

Next step for me is to update `run_tests.py` with new fields and update all tests I guess.

**Comment by X0rg** [comment]
I cleaned a bit the branch (to rebase and merge this time). Please review @anrieff.

**Review by anrieff — APPROVED** [review]
LGTM! Great work as always!

**Pull request merged**
