### PR TITLE
Add initial support for ARM CPUs

### PR DESCRIPTION
**Pull request by TheTumultuousUnicornOfDarkness**
I know #96 is opening since 7 years, but better late that never. ARM CPUs are more and more popular (Raspberry Pi, Apple M, and so on...) and some users demand ARM CPUs support, so I started to invest some time in such feature.

My goal is to add ARM support along side x86: libcpuid on ARM can decode x86 dumps, and vice-versa. The drawback is it requires a little more memory in `struct cpu_raw_data_t`, but I think it is acceptable.
Only ARM64 is supported because we cannot access MIDR from userspace in 32-bit mode. Linux and FreeBSD allow to access some EL1 registers in AArch64 mode, support for other OS is TBC. In other words, I do not see any way to support ARM CPUs up to ARMv7.

This PR adds logically more vendors in `enum cpu_vendor_t`  and more features in `enum cpu_feature_t`. There is `CPU_FEATURE_AES` on both x86 and ARM thus the error with consistency checks (I may update the check later).

In `struct cpu_id_t `, some fields do not have equivalent, that is why I added implementer/architecture_version/variant/part_num/revision. Some fields like family/model/ext_family/ext_model/stepping are x86 only. I do not know if the approach is correct, otherwise it will require a major change (like a union containing x86-specific and ARM-specific fields, depending on `architecture` value).
I tried to reuse some fields like `vendor_str` and `brand_str`, but these values are not stored in registers unlike x86.

Please note that we cannot decode cache information from userspace. I do not know if hardcoding all values for all ARM CPUs in the DB is a great idea, because the size is not fixed. Example for [Cortex-A55](https://developer.arm.com/Processors/Cortex-A55) :
- L1: 16KB to 64KB
- L2: Optional, 64KB to 256KB
- L3: Optional, 512KB to 4MB

Anyway, here is the `cpuid_tool` output for the Cortex-A57 CPU running on Debian 12 under a VM (QEMU TGC):
```
CPUID is present
CPU Info for type #0:
------------------
  arch       : ARM
  purpose    : general
  vendor_str : `ARM'
  vendor id  : 11
  brand_str  : `Cortex-A57'
  implementer: 65 (41h)
  arch_ver   : 15 (0Fh)
  variant    : 1 (01h)
  part_num   : 3335 (D07h)
  revision   : 0 (00h)
  num_cores  : 2
  num_logical: 2
  tot_logical: 2
  affi_mask  : 0x00000003
  features   : advsimd crc32 doublelock fp pmull sha1 sha256
```

@anrieff do you have time to provide a feedback? I plan to add more features (ARMv8.1 to ARMv8.9, and ARMv9.0 to ARMv9.4), I focused mostly on ARMv8.0 for now but it is just for the start. Work is required to support CPU topology (for big.LITTLE CPUs).
I use [Arm Architecture Reference Manual for A-profile architecture](https://developer.arm.com/documentation/ddi0487/latest/) as reference.

### CODE REVIEW

**Comment by TheTumultuousUnicornOfDarkness** [comment]
macOS does not allow to access EL1 registers:
```
/Users/runner/work/_temp/9f7b08bc-2a8a-459c-9461-d49e6b1338ae.sh: line 2:  3949 Illegal instruction: 4  ./build/cpuid_tool/cpuid_tool --save=-
```

**Comment by TheTumultuousUnicornOfDarkness** [comment]
I did a good progress targeting ARMv8/9-A in AArch64 mode, I added more than 2k LOC.

I replaced `arch_ver`  by `feat_level` to provide a more accurate information:
```
CPU Info for type #0:
------------------
  arch       : ARM
  feat_level : ARMv8.1-A
  purpose    : performance
  vendor_str : `ARM'
  vendor id  : 11
  brand_str  : `Cortex-A57'
  implementer: 65 (41h)
  variant    : 1 (01h)
  part_num   : 3335 (D07h)
  revision   : 0 (00h)
  num_cores  : 2
  num_logical: 4
  tot_logical: 4
  affi_mask  : 0x0000000F
  features   : advsimd crc32 doublelock fp pmull sha1 sha256 sm4 sve bbm dotprod fhm sel2
```

That is all I can do from userspace. I can write a kernel module to access registers not available from userspace, I found a good example [here](https://github.com/lelegard/arm-cpusysregs).

@anrieff I would like to know if my approach in `struct cpu_id_t` is OK for you? I mean by mixing x86/ARM data in `architecture`, `feature_level` and `flags` fields.

**Comment by anrieff** [comment]
All in all, great work! Libcpuid really needed this ARM extension.

> I did a good progress targeting ARMv8/9-A in AArch64 mode, I added more than 2k LOC.
> 
> I replaced `arch_ver` by `feat_level` to provide a more accurate information:
> 

I don't think we can reasonably add feature levels for the x86. x86 only has three "levels" per se: 8086, 80386 and x86_64. And we don't support 8086 anyway. The typical x86 way of handling instruction set additions is with flags. However, it would be inconvenient to do that for the ARM (using cpu_id_t::flags with CPU_FEATURE_LEVEL_ARM_V1, CPU_FEATURE_LEVEL_ARM_V2, ..., all mutually exclusive).

Maybe we should think more about this one. In any case, I suggest that `feat_level` is only printed by `cpuid_tool` for ARM. For x86 I believe would forever print "unknown", so it's not much useful.

> ```
> CPU Info for type #0:
> ------------------
>   arch       : ARM
>   feat_level : ARMv8.1-A
>   purpose    : performance
>   vendor_str : `ARM'
>   vendor id  : 11
>   brand_str  : `Cortex-A57'
>   implementer: 65 (41h)
>   variant    : 1 (01h)
>   part_num   : 3335 (D07h)
>   revision   : 0 (00h)
>   num_cores  : 2
>   num_logical: 4
>   tot_logical: 4
>   affi_mask  : 0x0000000F
>   features   : advsimd crc32 doublelock fp pmull sha1 sha256 sm4 sve bbm dotprod fhm sel2
> ```
> 

That's perfect! I will try a few of my ARM PCs today and report on how it looks there.

> That is all I can do from userspace. I can write a kernel module to access registers not available from userspace, I found a good example [here](https://github.com/lelegard/arm-cpusysregs).

Yeah, similar to the MSR I/O on windows. But this is better off in a separate PR.

> @anrieff I would like to know if my approach in `struct cpu_id_t` is OK for you? I mean by mixing x86/ARM data in `architecture`, `feature_level` and `flags` fields.

Yes, the architecture and flags is perfect. For the feature level, see above.

Using enums to save space: not really needed as the size savings are not relevant.
The question I think is mainly what makes more stylistic sense, e.g. consider

```
	struct cpu_id_t cpu;
	cpu_identify(NULL, &cpu);
	if (cpu.architecture == ARCHITECTURE_X86) {
		printf("X86 family: %d\n", cpu.x86.family);
		//...
	} else if (cpu.architecture == ARCHITECTURE_ARM) {
		printf("ARM implementer: %d\n", cpu.arm.implementer);
		//...
	}
```

Similar to e.g. SDL with how their SDL_Event is laid out.

I personally like this style better, but of course it will break all existing code using libcpuid that touches those fields. What's your take on this?

**Comment by TheTumultuousUnicornOfDarkness** [comment]
Thank you for your feedback!
> I don't think we can reasonably add feature levels for the x86. x86 only has three "levels" per se: 8086, 80386 and x86_64. And we don't support 8086 anyway. The typical x86 way of handling instruction set additions is with flags. However, it would be inconvenient to do that for the ARM (using cpu_id_t::flags with CPU_FEATURE_LEVEL_ARM_V1, CPU_FEATURE_LEVEL_ARM_V2, ..., all mutually exclusive).

The idea was to work on #177 later by adding `CPU_FEATURE_LEVEL_X86_64_V1` to `CPU_FEATURE_LEVEL_X86_64_V4` in fact.

> That's perfect! I will try a few of my ARM PCs today and report on how it looks there.

Nice, it would be great if you can share the RAW dump, because emulation is limited and QEMU seems to not present all features.

> > That is all I can do from userspace. I can write a kernel module to access registers not available from userspace, I found a good example [here](https://github.com/lelegard/arm-cpusysregs).
> 
> Yeah, similar to the MSR I/O on windows. But this is better off in a separate PR.

Exactly: it will be more or less like MSR code, excepted we will have to write our own driver for all OS (Windows, Linux, macOS and so on).

> Using enums to save space: not really needed as the size savings are not relevant. The question I think is mainly what makes more stylistic sense, e.g. consider
> 
> ```
> 	struct cpu_id_t cpu;
> 	cpu_identify(NULL, &cpu);
> 	if (cpu.architecture == ARCHITECTURE_X86) {
> 		printf("X86 family: %d\n", cpu.x86.family);
> 		//...
> 	} else if (cpu.architecture == ARCHITECTURE_ARM) {
> 		printf("ARM implementer: %d\n", cpu.arm.implementer);
> 		//...
> 	}
> ```
> 
> Similar to e.g. SDL with how their SDL_Event is laid out.
> 
> I personally like this style better, but of course it will break all existing code using libcpuid that touches those fields. What's your take on this?

Yeah, that is a good point, and it is a major point about the future of this project. libcpuid was designed for x86 only, and if we want a more generic library (for instance to support more CPU architectures like RISC-V, PowerPC...), we may need to refactor the library deeply.
I can work on a breaking change for `struct cpu_id_t` to move x86 specific stuff to a `x86` sub-struct, but it will break backward compatibility. It will become something like libcpuid v1.0.0 if we decide to work on a major change.

Generally speaking, I am grateful to you for allowing me to contribute to this project, but this is not my project so sometimes I am not sure what I can do or not. And I know you are very busy outside this project and you do not have much time left to devote to libcpuid, I fully understand.
For instance, I would like to drop support of deprecated features and get rid of Autohell and VS projects since we have CMake (and it is a burden to maintain all of them). So I am wondering if I can do anything I want here or if I should create a hard fork to be able to introduce backward-incompatibles changes and do a thorough overhaul.

**Comment by anrieff** [comment]
> The idea was to work on #177 later by adding `CPU_FEATURE_LEVEL_X86_64_V1` to `CPU_FEATURE_LEVEL_X86_64_V4` in fact.

Ah, I see, I have missed that. Yes, if people are requesting such a feature, then let's have it. The separation seems somewhat arbitrary though (because supporting AVX512 is one thing, having the 512-bit wide ALUs is another, and I would rather see V4 being equal to "I have the wide ALUs in silicon"). But if people see value in this - it's good.

> 
> Nice, it would be great if you can share the RAW dump, because emulation is limited and QEMU seems to not present all features.

Attached one from DragonBoard 410c
[raw.txt](https://github.com/user-attachments/files/15952074/raw.txt)

I tried getting a dump from 2 nVidia Jetsons, and the latest code from this branch complains about a missing CPUID instruction. Apparently `getauxval(AT_HWCAP) & HWCAP_CPUID` returns false. According to [this](https://github.com/OpenMathLib/OpenBLAS/issues/2715), it may be a bug. I have the Jetsons at my disposal, and can test anytime.

> Yeah, that is a good point, and it is a major point about the future of this project. libcpuid was designed for x86 only, and if we want a more generic library (for instance to support more CPU architectures like RISC-V, PowerPC...), we may need to refactor the library deeply. I can work on a breaking change for `struct cpu_id_t` to move x86 specific stuff to a `x86` sub-struct, but it will break backward compatibility. It will become something like libcpuid v1.0.0 if we decide to work on a major change.

It doesn't have to break all code: I think if we layout the structure correctly, it will be possible to make the old code still compile and still use cpu_id_t::family, and that maps to cpu_id_t::x86_id_t::family (or however we call it). So it may be a ABI-breaking change, but just recompiling the old code would fix that. As I said, we need to think about it more.

> Generally speaking, I am grateful to you for allowing me to contribute to this project, but this is not my project so sometimes I am not sure what I can do or not. And I know you are very busy outside this project and you do not have much time left to devote to libcpuid, I fully understand. For instance, I would like to drop support of deprecated features and get rid of Autohell and VS projects since we have CMake (and it is a burden to maintain all of them). So I am wondering if I can do anything I want here or if I should create a hard fork to be able to introduce backward-incompatibles changes and do a thorough overhaul.

I truly cherish contributors like you, which pump barrels of energy in projects like libcpuid. And yes, I understand that from your standpoint it is painful to maintain a project, which has a lot of legacy build systems, you don't feel completely free about its direction, and the project owner is hard to reach (at best of times).
It is ultimately your decision, as this is how the free software world operates. I still want to work on libcpuid and contribute new code and ideas, and of course life only gives you 18 awake hours a day, so you have to prioritize.

My suggestions though, are:
- If you want a chat/discussion that goes quicker than github/PR comments, I'm available on e-mail, or Signal, Telegram, Google Chat, etc.
- for Autohell and VS projects: a cornerstone in OSS development is you don't truly know your users and also don't really know what feature(s) do they use. There might be people that *like* libcpuid, because it has VS projects. You can do polls and/or ask people, but this starts to feel like a business, not OSS. In any case just dropping features without at least warning users with a release where this feature is marked as deprecated and will be removed in, e.g. 6 months, can backfire, because you can't estimate what % of your users you've burnt with that decision. For that reason, I vote for keeping those, and automating the maintenance part as much as possible - I can do that.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
> Attached one from DragonBoard 410c [raw.txt](https://github.com/user-attachments/files/15952074/raw.txt)

Thank you very much!
Cortex-A53 is ARMv8.0-A compliant, but was detected as ARMv8.1-A: I added a fix in 4b7da4257a59014bed19f46a6f819749f095d20c.
```
Check if CPU is ARMv8.0-A compliant:  4/41 optional features detected,  0/ 0 mandatory features required
Check if CPU is ARMv8.1-A compliant:  1/25 optional features detected,  1/ 5 mandatory features required
ARM architecture version is ARMv8.0-A
```

> I tried getting a dump from 2 nVidia Jetsons, and the latest code from this branch complains about a missing CPUID instruction. Apparently `getauxval(AT_HWCAP) & HWCAP_CPUID` returns false. According to [this](https://github.com/OpenMathLib/OpenBLAS/issues/2715), it may be a bug. I have the Jetsons at my disposal, and can test anytime.

I don't know if checking `HWCAP_CPUID` is a good idea, after all. There is a similar issue on FreeBSD: google/cpu_features#344
Maybe I can remove this check for ARM CPUs and trap SIGILL instead (like [here](https://stackoverflow.com/a/64867034)).

> It doesn't have to break all code: I think if we layout the structure correctly, it will be possible to make the old code still compile and still use cpu_id_t::family, and that maps to cpu_id_t::x86_id_t::family (or however we call it). So it may be a ABI-breaking change, but just recompiling the old code would fix that. As I said, we need to think about it more.

I see, I think you mean something like that: c2e8aa50c1c9981b285e84ce1414bf8b33ba7102).
I remember we did a similar thing in v0.5.0, when we added `cpu_id_t::l1_data_assoc` and `cpu_id_t::l1_data_cacheline` and deprecated `cpu_id_t::l1_assoc` and ` cpu_id_t::l1_cacheline`.

> I truly cherish contributors like you, which pump barrels of energy in projects like libcpuid. And yes, I understand that from your standpoint it is painful to maintain a project, which has a lot of legacy build systems, you don't feel completely free about its direction, and the project owner is hard to reach (at best of times). It is ultimately your decision, as this is how the free software world operates. I still want to work on libcpuid and contribute new code and ideas, and of course life only gives you 18 awake hours a day, so you have to prioritize.

Yeah, that is why a "hard fork" can make sense in one way, but it is a tough decision to make, and fragmentation in open source community is not a good thing I think.
It was just something to think about for myself.

> My suggestions though, are:
> 
>     * If you want a chat/discussion that goes quicker than github/PR comments, I'm available on e-mail, or Signal, Telegram, Google Chat, etc.

I do not want to disturb, but it is kind, thanks.

>     * for Autohell and VS projects: a cornerstone in OSS development is you don't truly know your users and also don't really know what feature(s) do they use. There might be people that _like_ libcpuid, because it has VS projects. You can do polls and/or ask people, but this starts to feel like a business, not OSS. In any case just dropping features without at least warning users with a release where this feature is marked as deprecated and will be removed in, e.g. 6 months, can backfire, because you can't estimate what % of your users you've burnt with that decision. For that reason, I vote for keeping those, and automating the maintenance part as much as possible - I can do that.

Ok, I had not thought about it that way, so let's keep them. Sometimes, I forget to update files like `exports.def`, `libcpuid.dsp` or VCproj files, but I think I was care enough this time.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
Stupid C++ does not support anonymous struct in anonymous union properly, I had this error when I built CPU-X (even if it is fine when I build libcpuid):
```
/usr/include/libcpuid/libcpuid.h:493:33: error: duplicate member 'family'
  493 |                         int32_t family;
      |                                 ^~~~~~
/usr/include/libcpuid/libcpuid.h:496:33: error: duplicate member 'model'
  496 |                         int32_t model;
      |                                 ^~~~~
/usr/include/libcpuid/libcpuid.h:499:33: error: duplicate member 'stepping'
  499 |                         int32_t stepping;
      |                                 ^~~~~~~~
/usr/include/libcpuid/libcpuid.h:502:33: error: duplicate member 'ext_family'
  502 |                         int32_t ext_family;
      |                                 ^~~~~~~~~~
/usr/include/libcpuid/libcpuid.h:508:33: error: duplicate member 'ext_model'
  508 |                         int32_t ext_model;
      |                                 ^~~~~~~~~
/usr/include/libcpuid/libcpuid.h:659:17: error: duplicate member 'sse_size'
  659 |         int32_t sse_size;
      |                 ^~~~~~~~
/usr/include/libcpuid/libcpuid.h:672:26: error: duplicate member 'sgx'
  672 |         struct cpu_sgx_t sgx;
      |  
```
I moved sub-struct declarations outside `struct cpu_id_t` in 76b306f350de8dfbf0fc1975e4993878669f5079, now g++ compiler is happy.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
I added some codenames and tests are now working for ARM CPUs.

I think the code is ready to be merged in master. @anrieff, any final thoughts before merging? These changes are backward compatibles.
I may work on kernel modules, caches detection and AArch32 support in a second time (in a new PR if you consider it necessary).

**Comment by anrieff** [comment]
Wonderful work!

You can merge now, but before making a release, it would be good to mark the deprecated `cpu_id_t` fields, with `__attribute__((deprecated))` (which only works on GCC and Clang, but maybe this is as good as it gets).

Since GCC shows the offending line, we can make it even better, by including the "how to fix this" hint in a comment on the same line, i.e. you can have something like

```
...
    int32_t sse_size LIBCPUID_DEPRECATED; /* replace with ".x86.sse_size" in your code to fix the warning */
...
```

**Comment by TheTumultuousUnicornOfDarkness** [comment]
> I also see two CPU cpu_feature_t's commented out (CPU_FEATURE_AA32HPD and CPU_FEATURE_AA32I8MM), what's the rub there?

Ah, yes, these features are supported in AArch32 state only, but I focused on AArch64, that is why I was not able to detect FEAT_AA32.
It will require a kernel module for AArch32 in order to use the `MRC` instruction.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
Manually merged in c5885699f0ec862fa43012ce92361c4b15687bc0 (GitHub Pull Requests are degraded right now).
Thank you for your time @anrieff!

**Pull request closed without merging**
