### PR TITLE
Add support for more CPUs

### PR DESCRIPTION
**Pull request by X0rg**
Hi,

I have added support for more CPUs (AMD & Intel), and correct 2-3 things.
Some links that helped me:
https://en.wikipedia.org/wiki/Bulldozer_%28microarchitecture%29
https://en.wikipedia.org/wiki/AMD_Accelerated_Processing_Unit
https://en.wikipedia.org/wiki/List_of_AMD_accelerated_processing_unit_microprocessors
https://en.wikipedia.org/wiki/Nehalem_%28microarchitecture%29
And a lot of screenshots found on Google Images.

Tell-me if you prefer to manually merge (if you want to merge).

### CODE REVIEW

**Comment by anrieff** [comment]
Thanks for your contribution.
Your changes to the code names break a few tests (the decoding logic is OK, just the CPU codenames are different, as you renamed them). Consider running `make test' to review the changes, and then `make fix-tests' if you agree with all of them.
Your text editor seems to modify the whitespace a lot - a big portion of the diff I'm getting is whitespace-related noise. You might want to turn off the WS handling options of it. At this state I cannot merge your branch right away. I may create a patch out of your branch with the '-w' option on, to discard WS-only changes, and apply that instead, if you're OK with that.

**Comment by X0rg** [comment]
I have renamed them because I was not understanding why certain codename are `Architecture (Family)` and others `Family (Architecture)`.
I'm sorry for WS, I use Medit and some options delete spaces at end of line and tabulations. Sure, I can turn them off to avoid this problem.
If you don't mind, I'm OK for your patch. Or I can do it later if you prefer.

**Comment by anrieff** [comment]
The codenames were really not very consistent, I was also thinking about rehauling them.
I'll merge it manually, and push it along with the test changes.

**Comment by X0rg** [comment]
Ok, thank you.

**Pull request closed without merging**
