### PR TITLE
Release version 0.5.0

### PR DESCRIPTION
**Pull request by X0rg**
Hello @anrieff,

Due to backwards-incompatible changes, we need to bump the library version.
- `cpu_raw_data_t`: add `amd_fn8000001dh` field;
- `cpu_id_t`: add `l1_{data,instruction}_{assoc,cacheline}` fields.

Since dfc8b2fdbd63e9fd7841538e649050a9104d0874, we have CI/CD enabled, so it will draft a new release if we push a new tag (note that the tag should be pushed only when all the jobs are successfully completed).

I let you review this pull request.

### CODE REVIEW

**Comment by X0rg** [comment]
@anrieff Ah, yes. About that, I am not sure it is necessary to keep this Debian source package, because as you know, it is a burden to maintain since we are not expert in Debian packaging system.

Libcpuid is present in official repositories now, so this version seems out of the date.
- Debian: https://packages.debian.org/source/bullseye/libcpuid
- Ubuntu: https://packages.ubuntu.com/source/focal/libcpuid

**Comment by anrieff** [comment]
Re: debian/ubuntu support, I think it's valuable to have it, and it's even more important to not leave devs with broken libcpuid installations if they installed via the packaging system and now the newest code is binary incompatible with their programs.
On debian/control: I think I got it. The number in the package name is the .so version (LIBCPUID_CURRENT from `configure.ac`). So as you bumped that to 15, then the new package names are `libcpuid15` and `libcpuid15-dev`, respectively, and they supplant libcpuid14.
I've pushed the change, to the pr_0.5.0 branch. I think this completes the release.

Can we merge the two commits into one when we merge in master? This will serve as a solid reference point how to do releases in the future.

**Comment by X0rg** [comment]
Ok, I understand. Also I renamed .install files.

> Can we merge the two commits into one when we merge in master? This will serve as a solid reference point how to do releases in the future.

@anrieff Yes, you can use the "Squash and merge" button for that. Or I can do that if you prefer.

**Comment by anrieff** [comment]
Cool, done.
Sorry for the slow communication these days, I was a bit off the grid. As always, thank you for invaluable contributions!

**Comment by X0rg** [comment]
No problem. :slightly_smiling_face: 
Now it is official, the [v0.5.0 is published](https://github.com/anrieff/libcpuid/releases/tag/v0.5.0)! :tada:

**Pull request merged**
